"""Executable guard for the client-facing guides.

Each test runs a documented walkthrough end-to-end through the real `filedge`
CLI and asserts on the *stable* parts of the output that the corresponding guide
shows — exit codes, key substrings, structural JSON keys — not exact bytes
(timestamps, UUIDs, durations, and latencies vary run to run).

The point is to make the guides un-driftable: if a code change alters an output
a guide depicts (a renamed flag, a removed summary field, a changed inference
tier, a rebranded header), the matching test here fails and prompts a doc
update. When you edit one of these guides' commands or output, update the
mirroring test in the same change.

Mirrors:
  docs/getting-started.md, docs/guides/inspect.md, docs/guides/validate.md,
  docs/guides/run.md, docs/guides/preview.md, docs/guides/healthcheck.md,
  docs/guides/compact.md, docs/guides/audit-export.md,
  docs/guides/fixed-width.md, docs/guides/quarantine.md
"""

import json

import pytest
from click.testing import CliRunner

from filedge.cli import cli


def _write(path, body):
    path.write_text(body)
    return str(path)


def _sqlite(tmp_path, name):
    return f"sqlite:///{tmp_path}/{name}"


_ORDERS_PIPELINE = """\
format: csv
dest_table: orders
write_mode: append
connector:
  type: sqlite
  url: {dest}
columns:
  - source: order_id
    dest: order_id
    type: string
    required: true
  - source: amount
    dest: amount
    type: float
    required: true
"""

_CLEAN_CSV = "order_id,amount\nORD-1,9.99\nORD-2,14.50\nORD-3,0.01\n"


def _orders_workspace(tmp_path):
    incoming = tmp_path / "incoming"
    incoming.mkdir()
    _write(incoming / "data.csv", _CLEAN_CSV)
    config = _write(
        tmp_path / "pipeline.yaml",
        _ORDERS_PIPELINE.format(dest=_sqlite(tmp_path, "orders.db")),
    )
    return str(incoming), config


# --- docs/getting-started.md ---------------------------------------------------

def test_getting_started_happy_path(tmp_path):
    """inspect -> validate -> run -> status, as Steps 1-4 show."""
    data = _write(tmp_path / "data.csv", _CLEAN_CSV)
    incoming, config = _orders_workspace(tmp_path)
    audit = _sqlite(tmp_path, "filedge.db")
    runner = CliRunner()

    # Step 1: inspect emits a filedge-branded YAML header (guards the #258 branding fix).
    insp = runner.invoke(cli, ["inspect", data])
    assert insp.exit_code == 0
    assert "# Generated by filedge inspect" in insp.output
    assert "columns:" in insp.output

    # Step 3: validate is clean and exits 0.
    val = runner.invoke(cli, ["validate", data, "--config", config])
    assert val.exit_code == 0
    assert "rows checked, no failures" in val.output

    # Step 4: run commits exactly one File.
    run = runner.invoke(
        cli, ["run", "--dir", incoming, "--config", config,
              "--audit-db-url", audit, "--no-progress"]
    )
    assert run.exit_code == 0
    assert "Committed: 1" in run.output

    # status reports it COMMITTED.
    status = runner.invoke(cli, ["status", "--audit-db-url", audit])
    assert status.exit_code == 0
    assert "COMMITTED:  1" in status.output


def test_getting_started_validate_failure(tmp_path):
    """The 'or with failures' block: bad rows -> exit 1 and a failure count."""
    config = _write(
        tmp_path / "pipeline.yaml",
        _ORDERS_PIPELINE.format(dest=_sqlite(tmp_path, "orders.db")),
    )
    bad = _write(tmp_path / "bad.csv", "order_id,amount\nORD-1,9.99\nORD-2,n/a\n")

    result = CliRunner().invoke(cli, ["validate", bad, "--config", config])

    assert result.exit_code == 1
    assert "failure(s) in" in result.output


# --- docs/guides/inspect.md -----------------------------------------------------

def test_inspect_confidence_tiers(tmp_path):
    """Confidence tiers as the guide depicts: clean text high, nulls low,
    mixed numeric/text ambiguous (guards #258)."""
    data = _write(
        tmp_path / "data.csv",
        "name,amount,code\n"
        "Alice,9.99,A\n"
        "Bob,,B\n"          # amount null -> low
        "Carol,3.50,7\n",   # code mixes text + numeric -> ambiguous
    )
    result = CliRunner().invoke(cli, ["inspect", data])

    assert result.exit_code == 0
    assert "name" in result.output and "string, high" in result.output
    assert "amount" in result.output and "float, low" in result.output
    assert "code" in result.output and "ambiguous" in result.output


# --- docs/guides/validate.md ----------------------------------------------------

def test_validate_json_shape(tmp_path):
    config = _write(
        tmp_path / "pipeline.yaml",
        _ORDERS_PIPELINE.format(dest=_sqlite(tmp_path, "orders.db")),
    )
    data = _write(tmp_path / "data.csv", _CLEAN_CSV)

    result = CliRunner().invoke(cli, ["validate", data, "--config", config, "--json"])

    assert result.exit_code == 0
    # The JSON line is the last line of stdout.
    payload = json.loads(result.output.strip().splitlines()[-1])
    assert set(payload) >= {"rows_checked", "failures", "undeclared_columns"}
    assert payload["rows_checked"] == 3
    assert payload["failures"] == []


# --- docs/guides/run.md ---------------------------------------------------------

def test_run_json_summary_fields(tmp_path):
    """The --json summary carries the fields run.md documents, incl.
    quarantined_rows (guards the field run.md was missing)."""
    incoming, config = _orders_workspace(tmp_path)
    audit = _sqlite(tmp_path, "filedge.db")

    result = CliRunner().invoke(
        cli, ["run", "--dir", incoming, "--config", config,
              "--audit-db-url", audit, "--json"]
    )

    assert result.exit_code == 0
    summary = json.loads(result.output.strip().splitlines()[-1])
    assert set(summary) >= {
        "run_id", "files_scanned", "new_files", "committed", "failed",
        "skipped", "reclaimed", "retried", "rows_committed",
        "quarantined_rows", "bytes_processed",
    }
    assert summary["committed"] == 1


# --- docs/guides/preview.md -----------------------------------------------------

def test_preview_renders_ascii_table(tmp_path):
    """preview renders an ASCII table (| + -), not box-drawing characters."""
    data = _write(
        tmp_path / "data.csv",
        "name,amount,order_date\nAlice,9.99,2024-01-15\nBob,14.50,2024-01-16\n",
    )
    result = CliRunner().invoke(cli, ["preview", data, "--rows", "2"])

    assert result.exit_code == 0
    assert "|" in result.output and "+" in result.output
    # No box-drawing characters leaked back in.
    for ch in ("│", "┼", "─"):
        assert ch not in result.output


# --- docs/guides/healthcheck.md -------------------------------------------------

def test_healthcheck_text_and_json(tmp_path):
    config = _write(
        tmp_path / "pipeline.yaml",
        _ORDERS_PIPELINE.format(dest=_sqlite(tmp_path, "orders.db")),
    )
    audit = _sqlite(tmp_path, "filedge.db")
    runner = CliRunner()

    text = runner.invoke(cli, ["healthcheck", "--config", config, "--audit-db-url", audit])
    assert text.exit_code == 0
    assert "audit_db: ok" in text.output
    assert "destination: ok" in text.output

    js = runner.invoke(
        cli, ["healthcheck", "--config", config, "--audit-db-url", audit, "--json"]
    )
    assert js.exit_code == 0
    payload = json.loads(js.output.strip().splitlines()[-1])
    assert payload["healthy"] is True
    assert {c["name"] for c in payload["checks"]} == {"audit_db", "destination"}


# --- docs/guides/audit-export.md ------------------------------------------------

def test_export_audit_writes_site(tmp_path):
    incoming, config = _orders_workspace(tmp_path)
    audit = _sqlite(tmp_path, "filedge.db")
    runner = CliRunner()
    runner.invoke(cli, ["run", "--dir", incoming, "--config", config,
                        "--audit-db-url", audit, "--no-progress"])

    out = tmp_path / "site" / "index.html"
    result = runner.invoke(cli, ["export-audit", "--audit-db-url", audit, "--output", str(out)])

    assert result.exit_code == 0
    assert "Exported 1 file records" in result.output
    assert out.exists()


# --- docs/guides/compact.md -----------------------------------------------------

def test_compact_merges_ndjson(tmp_path):
    incoming = tmp_path / "incoming"
    incoming.mkdir()
    _write(incoming / "a.ndjson", '{"id":"1"}\n{"id":"2"}\n')
    _write(incoming / "b.ndjson", '{"id":"3"}\n')
    out = tmp_path / "compacted"

    result = CliRunner().invoke(
        cli, ["compact", "--watched-dir", str(incoming), "--output", str(out)]
    )

    assert result.exit_code == 0
    assert "Files compacted: 2" in result.output
    merged = list(out.glob("*.ndjson"))
    assert len(merged) == 1
    assert len(merged[0].read_text().strip().splitlines()) == 3


# --- docs/guides/fixed-width.md -------------------------------------------------

_FW_PIPELINE = """\
format: fixed_width
dest_table: transactions
connector:
  type: sqlite
  url: {dest}
columns:
  - source: account_number
    dest: account_number
    type: string
    required: true
    start: 1
    width: 10
  - source: transaction_date
    dest: transaction_date
    type: date
    required: true
    start: 11
    width: 8
  - source: amount
    dest: amount_cents
    type: integer
    required: true
    start: 19
    width: 12
"""


def test_fixed_width_inspect_is_rejected(tmp_path):
    """inspect does not support fixed_width and says so (guide's CLI workflow)."""
    data = _write(tmp_path / "txns.fwf", "ACCT00000120240115000000150000\n")
    result = CliRunner().invoke(cli, ["inspect", data, "--format", "fixed_width"])

    assert result.exit_code != 0
    assert "does not support fixed_width" in result.output


def test_fixed_width_run_coerces_compact_date(tmp_path):
    """A YYYYMMDD field under a date column ingests and stores ISO YYYY-MM-DD."""
    landing = tmp_path / "landing"
    landing.mkdir()
    _write(landing / "txns.fwf", "ACCT00000120240115000000150000\n")
    config = _write(
        tmp_path / "pipeline.yaml",
        _FW_PIPELINE.format(dest=_sqlite(tmp_path, "fw.db")),
    )
    audit = _sqlite(tmp_path, "fw-audit.db")

    result = CliRunner().invoke(
        cli, ["run", "--dir", str(landing), "--config", config,
              "--audit-db-url", audit, "--no-progress"]
    )

    assert result.exit_code == 0
    assert "Committed: 1" in result.output

    import sqlite3
    row = sqlite3.connect(f"{tmp_path}/fw.db").execute(
        "select transaction_date, amount_cents from transactions"
    ).fetchone()
    assert row == ("2024-01-15", 150000)


# --- docs/guides/quarantine.md (the "Try the full loop" walkthrough) ------------

_QUARANTINE_PIPELINE = """\
format: ndjson
dest_table: partner_facts
connector:
  type: sqlite
  url: {dest}
quarantine:
  enabled: true
  dir: {qdir}
  max_invalid_fraction: 0.5
  max_invalid_rows: 100
columns:
  - source: filed
    dest: filed
    type: string
    required: true
  - source: val
    dest: value
    type: float
    required: true
"""

_PARTNER_NDJSON = (
    '{"filed": "2024-11-01", "val": 391035000000}\n'
    '{"filed": "2024-11-01", "val": "n/a"}\n'
    '{"filed": "2024-08-01", "val": 85777000000}\n'
    '{"filed": "2024-05-01", "val": ""}\n'
    '{"filed": "2024-02-01", "val": 119575000000}\n'
)


def test_quarantine_full_loop(tmp_path):
    """partial commit -> status -> audit export badge -> re-drop, as the
    quarantine guide's walkthrough shows (guards #252 and #253)."""
    landing = tmp_path / "qland"
    landing.mkdir()
    _write(landing / "partner-facts.ndjson", _PARTNER_NDJSON)
    qdir = tmp_path / "quarantine"
    config = _write(
        tmp_path / "pipeline.yaml",
        _QUARANTINE_PIPELINE.format(dest=_sqlite(tmp_path, "dest.db"), qdir=qdir),
    )
    audit = _sqlite(tmp_path, "audit.db")
    runner = CliRunner()

    # Run: 3 good rows commit, 2 bad rows quarantine (under the 50% threshold).
    run = runner.invoke(
        cli, ["run", "--dir", str(landing), "--config", config,
              "--audit-db-url", audit, "--no-progress"]
    )
    assert run.exit_code == 0
    assert "Quarantined rows: 2" in run.output

    # status surfaces the quarantined total.
    status = runner.invoke(cli, ["status", "--audit-db-url", audit])
    assert "QUARANTINED ROWS: 2" in status.output

    # Audit Export badges the partial commit and shows the sidecar path (#252).
    site = tmp_path / "site" / "index.html"
    runner.invoke(cli, ["export-audit", "--audit-db-url", audit, "--output", str(site)])
    html = site.read_text()
    assert "quarantined" in html
    assert ".quarantine.ndjson" in html

    # re-drop unwraps the sidecar into a clean NDJSON File (#253).
    sidecar = next(qdir.glob("*.quarantine.ndjson"))
    redrop = runner.invoke(cli, ["redrop-quarantine", "--sidecar", str(sidecar)])
    assert redrop.exit_code == 0
    assert "Wrote 2 row(s)" in redrop.output
