from datetime import datetime

from etl.inferrer import InferredColumn

_MARKER = "! "
_NO_MARKER = "  "
_MAX_NAME = 38


def format_yaml(columns: list[InferredColumn], source_path: str, sample_rows: int) -> str:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        f"# Generated by etl inspect",
        f"# source: {source_path}",
        f"# sample_rows: {sample_rows}",
        f"# timestamp: {ts}",
        "columns:",
    ]
    for col in columns:
        lines.append(f"  - source: {col.name}")
        lines.append(f"    dest: {col.name}")
        lines.append(f"    type: {col.inferred_type}")
        lines.append(f"    required: {'true' if col.null_count == 0 else 'false'}")
    return "\n".join(lines) + "\n"


def format_summary(columns: list[InferredColumn]) -> str:
    lines = []
    for col in columns:
        marker = _NO_MARKER if col.confidence == "high" else _MARKER
        name = col.name if len(col.name) <= _MAX_NAME else col.name[:_MAX_NAME - 1] + "…"
        null_info = f"nulls={col.null_count}" if col.null_count else ""
        parts = [p for p in [col.inferred_type, col.confidence, null_info] if p]
        row = f"{marker}{name:<{_MAX_NAME}}  {', '.join(parts)}"
        if len(row) > 80:
            row = row[:79] + "…"
        lines.append(row)
        for note in col.notes:
            note_line = f"    {note}"
            if len(note_line) > 80:
                note_line = note_line[:79] + "…"
            lines.append(note_line)
    return "\n".join(lines)
